services:
  frontend:
    image: busybox:1.36
    command: httpd -f -p 80 -h /www
    volumes:
      - ./game/:/www:ro
    networks:
      - caddy
    restart: unless-stopped
    labels:
      caddy: $DOMAIN
      caddy.header: Cache-Control no-cache
      caddy.redir: /game/dino_runner /game/dino_runner/ 302
      caddy.handle_path: /game/dino_runner/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - "./backend/app:/code/app"
    networks:
      - caddy
      - backend
    restart: unless-stopped
    labels:
      caddy: $DOMAIN
      caddy.header: Cache-Control no-cache
      caddy.handle_path: /game/dino_runner/api/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"

  redis:
    image: redis:8.8-alpine
    networks:
      - backend

volumes:
  redis-data:

networks:
  caddy:
    external: true
  backend:
