services:
  frontend:
    image: busybox:1.36
    command: httpd -f -p 80 -h /www
    volumes:
      - ./game/:/www:ro
    networks:
      - caddy
    restart: unless-stopped
    labels:
      caddy: $DOMAIN
      caddy.header: Cache-Control no-cache
      caddy.redir: /game/dino_runner /game/dino_runner/ 302
      caddy.handle_path: /game/dino_runner/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - "./backend/app:/code/app"
    networks:
      - caddy
      - backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    labels:
      caddy: $DOMAIN
      caddy.header: Cache-Control no-cache
      caddy.handle_path: /game/dino_runner/api/*
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"

  redis:
    image: redis:8.8-alpine
    volumes:
      - redis-data:/data
    networks:
      - backend
    restart: unless-stopped

  postgresql:
    image: postgres:18.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql
    networks:
      - backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

volumes:
  redis-data:
  pg-data:

networks:
  caddy:
    external: true
  backend:
